spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: subbu@jarvis10

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect